### ISSUE TITLE
Image display in docx output

### ISSUE THREAD

**Issue by devironl** [erezlife/html2docx#54]
Hello,

While running the program on my html file, the image is not displayed in the output file and I get the following output :

![image](https://user-images.githubusercontent.com/17426845/83530208-b211c400-a4eb-11ea-8061-18774fd450de.png)

Here is the original HTML code:

![image](https://user-images.githubusercontent.com/17426845/83530381-f1d8ab80-a4eb-11ea-9ec4-a78b8d2bc8a5.png)

And here is my code:

`
with open(f"html_file.html") as fp:
    html = fp.read()
    buf = html2docx(html, title="Test")

with open(f"docx_file.docx", "wb") as fp:
    fp.write(buf.getvalue())`

Am I doing something wrong ?

Thanks,

Louis

**Comment by francoisfreitag** [comment]
Hi Louis,

Pointing to local file images is not supported. The URI of your image should be absolute so that `html2docx` can retrieve it over the network. In the context of an HTML document, the library cannot guess where the image is hosted.
- If the image is publicly hosted, replacing `test.png` with the absolute url to the image should solve your issue.
- If the image is not hosted publicly, the library supports [data URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), which allows you to embed your image as part of the HTML document.

**Comment by devironl** [comment]
Hi François,
Thank you for your quick response !
The fix with the URIs works
Thanks again
Louis
